objects/Breakfeast__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Burger</fullName>
                </value>
                <value>
                    <fullName>Chips</fullName>
                </value>
                <value>
                    <fullName>Pizza</fullName>
                </value>
                <value>
                    <fullName>Kebab</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Qty__c</fullName>
        <label>Qty</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Breakfeast</label>
    <nameField>
        <displayFormat>v-{00000}</displayFormat>
        <label>Breakfeast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Breakfeast</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/brkTRGHandlerTest.cls
@isTest
public class brkTRGHandlerTest {
    
        @isTest static void Test1Test()
    {
        Breakfeast__c t3 = new Breakfeast__c();
        t3.Product__c = 'Burger';
        t3.Rate__c = 2.99;
        t3.Qty__c = 3;
        
        Insert t3;
        
        List<Breakfeast__c> b = New List<Breakfeast__c>([select id,price__c from Breakfeast__c where id =: t3.id]);
    	
         /**
			* Calculate Price Based on Rate and QTY
			* Assert Expected Value
			* @author MOC
			*/ 
        //System.assertEquals(8.97, b[0].price__c,'Price not Calculated Correctly');
        
    }

}