objects/Breakfeast__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Qty__c</fullName>
        <label>Qty</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Breakfeast</label>
    <nameField>
        <displayFormat>v-{00000}</displayFormat>
        <label>Breakfeast Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Breakfeast</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/brkTRGHandler.cls
public class brkTRGHandler {
    
        public static void calcPrice(List<Breakfeast__c> lstofzc){
         for(Breakfeast__c a : lstofzc) {
         	a.price__c = a.qty__c * a.rate__c;
    	}
        }
    
         public static void calcPrice2(List<Breakfeast__c> lstofzc){
         for(Breakfeast__c a : lstofzc) {
         	a.price__c = (a.qty__c * a.rate__c)*2;
    	}
        }
            

}