objects/Emirates__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Hummus</fullName>
                </value>
                <value>
                    <fullName>Halloumi</fullName>
                </value>
                <value>
                    <fullName>Falafel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Qty__c</fullName>
        <label>Qty</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Emirates</label>
    <nameField>
        <label>Emirates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Emirates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/emrTest.cls
@istest
public class emrTest {
    
        @isTest static void Test1Test()
    {
        Emirates__c t3 = new Emirates__c();
        t3.Product__c = 'Hummus';
        t3.Rate__c = 2.99;
        t3.Qty__c = 3;
        
        Insert t3;
        
        List<Emirates__c> b = New List<Emirates__c>([select id,price__c from Emirates__c where id =: t3.id]);
    	
        // Now Calculate Price and assert expected Value
        //System.assertEquals(8.97, b[0].price__c,'Price not Calculated Correctly');
        
    }

}