objects/TestObject__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Burger</fullName>
                </value>
                <value>
                    <fullName>Chips</fullName>
                </value>
                <value>
                    <fullName>Pizza</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Qty__c</fullName>
        <label>Qty</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>TestObject</label>
    <nameField>
        <label>TestObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TestObject</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

main/default/classes/TestObject_Test.cls
/**
 * @author moc <moc@polsource.com>
 * Comment line 2
 * Comment line 3
 */
@istest
public class TestObject_Test {
    @isTest static void test1Test()
    {
        TestObject__c t3 = new TestObject__c();
        t3.Product__c = 'Burger';
        t3.Rate__c = 2.99;
        t3.Qty__c = 3;
        
        Insert t3;
        
        List<TestObject__c> b = New List<TestObject__c>([select id,price__c from TestObject__c where id =: t3.id]);
    	
         /**
			* Calculate Price Based on Rate and QTY
			* Assert Expected Value
			* @author MOC
			*/ 
        System.assertEquals(8.97, b[0].price__c,'Price not Calculated Correctly');
        
    }
}