objects/Test2__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Burger</fullName>
                </value>
                <value>
                    <fullName>Kebab</fullName>
                </value>
                <value>
                    <fullName>Pizza</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Qty__c</fullName>
        <label>Qty</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Test2</label>
    <nameField>
        <label>Test2 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test2</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test2trg_Test.cls
@istest
public class Test2trg_Test {
    @isTest static void Test1Test()
    {
        Test2__c t3 = new Test2__c();
        t3.Product__c = 'Burger';
        t3.Rate__c = 2.99;
        t3.Qty__c = 3;
        
        Insert t3;
        
        List<Test2__c> b = New List<Test2__c>([select id,price__c from Test2__c where id =: t3.id]);
    	//System.assertEquals(8.96, b[0].price__c,'Price not Calculated Correctly');
        
        //System.assertEquals(8.97, b[0].price__c,'Price not Calculated Correctly');
        
    }
}