objects/VeraStar__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pizza</fullName>
                </value>
                <value>
                    <fullName>Kebab</fullName>
                </value>
                <value>
                    <fullName>Burger</fullName>
                </value>
                <value>
                    <fullName>Chorizo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Qty__c</fullName>
        <label>Qty</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>VeraStar</label>
    <nameField>
        <displayFormat>v-{00000}</displayFormat>
        <label>VeraStar Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>VeraStar</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/verastarTest.cls
/**
 * @author moc <moc@polsource.com>
 * Comment line 2
 * Comment line 3
 */
@istest
public class verastarTest {
        @isTest static void Test1Test()
    {
        verastar__c t3 = new verastar__c();
        t3.Product__c = 'Burger';
        t3.Rate__c = 2.99;
        t3.Qty__c = 3;
        
        Insert t3;
        
        List<verastar__c> b = New List<verastar__c>([select id,price__c from verastar__c where id =: t3.id]);
    	
        // Now Calculate Price and assert expected Value
        System.assertEquals(8.97, b[0].price__c,'Price not Calculated Correctly');
        
    }

}