objects/zConference__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Burger</fullName>
                </value>
                <value>
                    <fullName>Pizza</fullName>
                </value>
                <value>
                    <fullName>Kebab</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Qty__c</fullName>
        <label>Qty</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>zConference</label>
    <nameField>
        <label>zConference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>zConference</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/zConfTest.cls
/**
 * @author moc <moc@polsource.com>
 * Comment line 2
 * Comment line 3
 */
@istest
public class zConfTest {
    
    @isTest static void Test1Test()
    {
        zConference__c t3 = new zConference__c();
        t3.Product__c = 'Burger';
        t3.Rate__c = 2.99;
        t3.Qty__c = 3;
        
        Insert t3;
        
        List<zConference__c> b = New List<zConference__c>([select id,price__c from zConference__c where id =: t3.id]);
    	
         /**
			* Calculate Price Based on Rate and QTY
			* Assert Expected Value
			* @author MOC
			*/ 
        System.assertEquals(8.97, b[0].price__c,'Price not Calculated Correctly');
        
    }

}